### ISSUE TITLE
getByStrPath / getByPath don't seem to work with trees

### ISSUE THREAD

**Issue by mwildehahn** [loro-dev/loro-swift#4]
Doing:
```
doc.getByStrPath("root")
```

works and returns the tree as a value, but I can't figure out how to get at elements within it. I've tried:

```
doc.getByStrPath("root[0]") -> nil
doc.getByStrPath("root.children[0]") -> nil
```

am I getting the path wrong or this doesn't work with trees?

**Comment by mwildehahn** [comment]
It looks like this works with getByPath with a `TreeId` so maybe just not something you can do with the `getByStrPath`?

**Comment by zxch3n** [comment]
`tree[index]` doesn't work at the moment. But I think we can make it work! I'll give it a try.

**Comment by mwildehahn** [comment]
not a huge deal! this is mostly just useful in tests where i'm trying to assert the state of the tree
